production:
  environment: production
  production_environment: true

staging:
  auto_deploy_on: refs/heads/master
  environment: staging
  production_environment: false

review:
  # Set the transient environment flag to let GitHub and Deliverybot know that
  # this environment should be destroyed when the PR is closed.
  transient_environment: true
  production_environment: false

  # Dynamic environment name. The environment will look like pr123.
  environment: pr${{ pr }}
