baseurl = "https://voteforpolicies.org.uk"
title = "Vote For Policies"
languageCode = "en-gb"

enableGitInfo = true
enableEmoji = true

[params.meta]
  description = ""
  keywords = ""

[markup]
  defaultMarkdownHandler = "goldmark"
  [markup.goldmark]
    [markup.goldmark.extensions]
      definitionList = true
      footnote = true
      linkify = true
      strikethrough = true
      table = true
      taskList = true
      typographer = true
    [markup.goldmark.parser]
      attribute = true
      autoHeadingID = true
    [markup.goldmark.renderer]
      hardWraps = true
      unsafe = true
      xHTML = true
