backend:
  name: github
  repo: VJftw/vote-for-policies
  base_url: https://netlifycmsoauth.vfp.vjpatel.me
publish_mode: editorial_workflow # make a PR
media_folder: site/static/uploads
public_folder: /uploads
locale: "en"
collections:
  - name: "blog"
    label: "Blog"
    folder: "site/content/blog"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    editor:
      preview: true
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Description", name: "description", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }
  - name: "about"
    label: "About"
    folder: "site/content/about"
    create: true
    slug: "{{slug}}"
    editor:
      preview: true
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }
  - name: "contact"
    label: "Contact"
    folder: "site/content/contact"
    create: true
    slug: "{{slug}}"
    editor:
      preview: true
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }
  - name: "donate"
    label: "Donate"
    folder: "site/content/donate"
    create: true
    slug: "{{slug}}"
    editor:
      preview: true
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }
