---
name: Deploy
on: ['deployment']

jobs:
  deployment:
    runs-on: ubuntu-latest
    steps:
      - name: "Deployment pending"
        uses: "deliverybot/deployment-status@master"
        with:
          state: "pending"
          token: "${{ github.token }}"

      - name: Set up Node
        uses: actions/setup-node@v1
        with:
          node-version: 14.x

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Check out code
        uses: actions/checkout@v2

      - name: Install NPM dependencies
        run: npm install

      - name: "Deploy ${{ github.event.deployment.environment }}"
        run: scripts/deploy.sh ${{ github.event.deployment.environment }}

      - name: "Deployment success"
        if: success()
        uses: "deliverybot/deployment-status@master"
        with:
          state: "success"
          token: "${{ github.token }}"

      - name: "Deployment failure"
        if: failure()
        uses: "deliverybot/deployment-status@master"
        with:
          state: "failure"
          token: "${{ github.token }}"
