name: PRCleanup
on:
  pull_request:
    types: [closed]

jobs:
  pr-close:
    runs-on: 'ubuntu-latest'
    steps:
      - name: Set up Node
        uses: actions/setup-node@v1
        with:
          node-version: 14.x

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      
      - name: Check out code
        uses: actions/checkout@v2
  
      - name: Install NPM dependencies
        run: npm install

      - name: "Undeploy pr${{ github.event.pull_request.number }}"
        run: scripts/undeploy.sh pr${{ github.event.pull_request.number }}
  